# SONGS
# 
# 
### Hello World!
GET http://localhost:3000/

### findAll
GET http://localhost:3000/songs?page=1&limit=2

### findById
GET http://localhost:3000/songs/3

### create
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "7empest",
    "artistsIds": [1],
    "releaseDate": "2021-01-01",
    "duration": "07:30",
    "lyrics": ""
}

### updateById
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
    # "title": "Pneuma",
    # "artists": ["TOOL"],
    # "releaseDate": "2021-01-01",
    # "duration": "03:30",
    "lyrics": "We are spirit bound to this flesh"
}

### deleteById
DELETE http://localhost:3000/songs/2


# PLAYLISTS
# 
# 

### create playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "Chill Out",
    "songsIds": [1, 2, 3],
    "userId": 1
}

# USERS
# 
# 

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "john",
"lastName": "doe",
"email": "john1@gmail.com",
"password": "123456"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john1@gmail.com",
"password": "123456"
}